# =============================================================================
# SecurityContextConstraints for LLM Benchmark
# =============================================================================
# Grant privileged access to bench-sa service account
# Required for GPU workloads on some OpenShift configurations
# =============================================================================
---
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: llm-bench-scc
  namespace: gpu1
  labels:
    app.kubernetes.io/part-of: llm-benchmark
spec:
  workload:
    manifests:
      # RoleBinding to allow privileged SCC
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: llm-bench-privileged
          namespace: llm-bench
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: system:openshift:scc:privileged
        subjects:
        - kind: ServiceAccount
          name: bench-sa
          namespace: llm-bench
      # Also bind anyuid SCC
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: llm-bench-anyuid
          namespace: llm-bench
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: system:openshift:scc:anyuid
        subjects:
        - kind: ServiceAccount
          name: bench-sa
          namespace: llm-bench
